packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  '@bundled-es-modules/glob': true
  esbuild: true
  style-dictionary: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.23 || 57.0.24'
  - '@expo/metro-file-map@57.0.3'
  - babel-preset-expo@57.0.11
  - expo-modules-core@57.0.17 || 57.0.18
  - expo-modules-jsi@57.1.0
  - expo@57.0.21 || 57.0.22
  - '@expo/fingerprint@0.20.13'
  - '@expo/prebuild-config@57.0.16'
  - expo-asset@57.0.17
  - expo-constants@57.0.18
  - expo-file-system@57.0.7
  - expo-font@57.0.4
  - expo-keep-awake@57.0.2
  - expo-modules-autolinking@57.0.13
onlyBuiltDependencies:
  - '@bundled-es-modules/glob'
  - style-dictionary
