import StyleDictionary from 'style-dictionary';
import { cpSync, mkdirSync, readdirSync, rmSync, writeFileSync, readFileSync } from 'node:fs';

const PRESETS = [
  'hi-vis',
  'sea-glass',
  'bauhaus',
  'earthy',
  'tropical',
  'sunset-berry',
  'bodega',
  'indigo-pop',
];
const MODES = ['light', 'dark'];

rmSync('./src/generated', { recursive: true, force: true });
rmSync('./dist', { recursive: true, force: true });
mkdirSync('./src/generated', { recursive: true });
mkdirSync('./dist/fonts', { recursive: true });
for (const file of readdirSync('./fonts')) {
  cpSync(`./fonts/${file}`, `./dist/fonts/${file}`);
}

StyleDictionary.registerTransform({
  name: 'valence/strip-unit',
  type: 'value',
  filter: (token) => typeof token.value === 'string' && /^-?[\d.]+(px|em)$/.test(token.value),
  transform: (token) => parseFloat(token.value),
});

const NATIVE_TYPE_SCALE = 16 / 14;
StyleDictionary.registerTransform({
  name: 'valence/native-type-scale',
  type: 'value',
  filter: (token) => token.attributes?.category === 'type' && token.attributes?.item === 'size',
  transform: (token) => Math.round(token.value * NATIVE_TYPE_SCALE),
});

StyleDictionary.registerFormat({
  name: 'typescript/flat-theme',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map((token) => {
      const value = typeof token.value === 'number' ? token.value : JSON.stringify(token.value);

      return `  ${token.name}: ${value},`;
    });

    return `// Generated by build.mjs — do not edit by hand.\nexport const theme: {\n${dictionary.allTokens
      .map((t) => `  ${t.name}: ${typeof t.value === 'number' ? 'number' : 'string'};`)
      .join('\n')}\n} = {\n${lines.join('\n')}\n};\n`;
  },
});

async function buildVariant(preset, mode) {
  const sd = new StyleDictionary({
    source: [`tokens/shared/**/*.json`, `tokens/themes/${preset}/${mode}/**/*.json`],
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath: 'dist/css/',
        files: [
          {
            destination: `${preset}-${mode}.css`,
            format: 'css/variables',
            options: {
              selector: `[data-preset="${preset}"][data-theme="${mode}"]`,
            },
          },
        ],
      },
      ts: {
        transforms: [
          'attribute/cti',
          'name/camel',
          'valence/strip-unit',
          'valence/native-type-scale',
        ],
        buildPath: 'src/generated/',
        files: [{ destination: `${preset}-${mode}.ts`, format: 'typescript/flat-theme' }],
      },
    },
  });

  await sd.buildAllPlatforms();
}

for (const preset of PRESETS) {
  for (const mode of MODES) {
    await buildVariant(preset, mode);
  }
}

StyleDictionary.registerFormat({
  name: 'typescript/color-keys',
  format: ({ dictionary }) => {
    const names = dictionary.allTokens
      .filter((token) => token.attributes.category === 'color')
      .map((token) => token.name);

    return `// Generated by build.mjs — do not edit by hand.\nexport type ThemeColorKey = ${names
      .map((name) => `'${name}'`)
      .join(' | ')};\n`;
  },
});

await new StyleDictionary({
  source: ['tokens/shared/**/*.json', 'tokens/themes/hi-vis/light/**/*.json'],
  platforms: {
    ts: {
      transforms: ['attribute/cti', 'name/camel', 'valence/strip-unit'],
      buildPath: 'src/generated/',
      files: [{ destination: 'theme-color-keys.ts', format: 'typescript/color-keys' }],
    },
  },
}).buildAllPlatforms();

async function buildDefault(mode, selector, destination) {
  const sd = new StyleDictionary({
    source: [`tokens/shared/**/*.json`, `tokens/themes/hi-vis/${mode}/**/*.json`],
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath: 'dist/css/',
        files: [{ destination, format: 'css/variables', options: { selector } }],
      },
    },
  });

  await sd.buildAllPlatforms();
}

await buildDefault('light', ':root', 'default-light.css');

await buildDefault('dark', '[data-theme="dark"]', 'default-dark.css');

const combined = [
  readFileSync('dist/css/default-light.css', 'utf8'),
  readFileSync('dist/css/default-dark.css', 'utf8'),
  ...PRESETS.flatMap((preset) =>
    MODES.map((mode) => readFileSync(`dist/css/${preset}-${mode}.css`, 'utf8')),
  ),
].join('\n');
writeFileSync(
  'dist/css/tokens.css',
  `/* Generated by build.mjs — do not edit by hand. */\n\n${combined}`,
);

console.log(
  `Tokens built: dist/css/tokens.css, src/generated/{${PRESETS.map((p) => `${p}-{light,dark}`).join(',')}}.ts`,
);
