// The native theme object has no Style Dictionary built-in format, so it's
// produced by the custom format registered below.
import StyleDictionary from 'style-dictionary';
import { cpSync, mkdirSync, readdirSync, rmSync, writeFileSync, readFileSync } from 'node:fs';

const PRESETS = [
  'hi-vis',
  'sea-glass',
  'bauhaus',
  'earthy',
  'tropical',
  'sunset-berry',
  'bodega',
  'indigo-pop',
];
const MODES = ['light', 'dark'];

// Clear owned output before regenerating — otherwise a renamed/removed
// preset or font leaves its old file orphaned, and since dist/ ships in
// full to npm, that orphan publishes forever.
rmSync('./src/generated', { recursive: true, force: true });
rmSync('./dist', { recursive: true, force: true });
mkdirSync('./src/generated', { recursive: true });
mkdirSync('./dist/fonts', { recursive: true });
for (const file of readdirSync('./fonts')) {
  cpSync(`./fonts/${file}`, `./dist/fonts/${file}`);
}

// Dimension tokens are authored with CSS units (the DTCG convention) so the
// css platform can pass them through unchanged. Native has no unit syntax —
// RN dimensions are unitless dp, and letterSpacing is unitless points — so
// this transform strips the suffix back to a plain number for the ts
// platform only. `em` tracking values become a bare em-fraction; the
// Text-rendering components multiply by their own fontSize at render time
// to get RN's absolute letterSpacing (the same thing the browser does
// implicitly for CSS em units).
StyleDictionary.registerTransform({
  name: 'valence/strip-unit',
  type: 'value',
  filter: (token) => typeof token.value === 'string' && /^-?[\d.]+(px|em)$/.test(token.value),
  transform: (token) => parseFloat(token.value),
});

// Native renders the type scale slightly larger than web, anchored on
// body: 14 -> 16 (matching Material's default body-text size) and applied
// as one ratio to every type.*.size token, so the scale's relative
// hierarchy stays intact rather than each tier being picked by hand.
const NATIVE_TYPE_SCALE = 16 / 14;
StyleDictionary.registerTransform({
  name: 'valence/native-type-scale',
  type: 'value',
  filter: (token) => token.attributes?.category === 'type' && token.attributes?.item === 'size',
  transform: (token) => Math.round(token.value * NATIVE_TYPE_SCALE),
});

StyleDictionary.registerFormat({
  name: 'typescript/flat-theme',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map((token) => {
      const value = typeof token.value === 'number' ? token.value : JSON.stringify(token.value);

      return `  ${token.name}: ${value},`;
    });

    return `// Generated by build.mjs — do not edit by hand.\nexport const theme: {\n${dictionary.allTokens
      .map((t) => `  ${t.name}: ${typeof t.value === 'number' ? 'number' : 'string'};`)
      .join('\n')}\n} = {\n${lines.join('\n')}\n};\n`;
  },
});

async function buildVariant(preset, mode) {
  const sd = new StyleDictionary({
    source: [`tokens/shared/**/*.json`, `tokens/themes/${preset}/${mode}/**/*.json`],
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath: 'dist/css/',
        files: [
          {
            destination: `${preset}-${mode}.css`,
            format: 'css/variables',
            options: {
              selector: `[data-preset="${preset}"][data-theme="${mode}"]`,
            },
          },
        ],
      },
      ts: {
        transforms: [
          'attribute/cti',
          'name/snake',
          'valence/strip-unit',
          'valence/native-type-scale',
        ],
        buildPath: 'src/generated/',
        files: [{ destination: `${preset}-${mode}.ts`, format: 'typescript/flat-theme' }],
      },
    },
  });

  await sd.buildAllPlatforms();
}

for (const preset of PRESETS) {
  for (const mode of MODES) {
    await buildVariant(preset, mode);
  }
}

// Runtime theme overrides are only safe for color tokens — non-color
// dimensions need units on web (e.g. `8px`) that a raw override value can't
// supply. Key names are identical across every preset/mode, so any one of
// them is enough to derive the list; `attribute/cti` sets `category` from
// each token's top-level JSON key (color.json's is "color").
StyleDictionary.registerFormat({
  name: 'typescript/color-keys',
  format: ({ dictionary }) => {
    const names = dictionary.allTokens
      .filter((token) => token.attributes.category === 'color')
      .map((token) => token.name);

    return `// Generated by build.mjs — do not edit by hand.\nexport type ThemeColorKey = ${names
      .map((name) => `'${name}'`)
      .join(' | ')};\n`;
  },
});

await new StyleDictionary({
  source: ['tokens/shared/**/*.json', 'tokens/themes/hi-vis/light/**/*.json'],
  platforms: {
    ts: {
      transforms: ['attribute/cti', 'name/snake', 'valence/strip-unit'],
      buildPath: 'src/generated/',
      files: [{ destination: 'theme-color-keys.ts', format: 'typescript/color-keys' }],
    },
  },
}).buildAllPlatforms();

// hi-vis (the default preset) also gets bare `:root` / `[data-theme="dark"]`
// selectors with no `data-preset` needed, so a consumer that sets a mode but
// never picks a preset still gets a themed page instead of unstyled content.
async function buildDefault(mode, selector, destination) {
  const sd = new StyleDictionary({
    source: [`tokens/shared/**/*.json`, `tokens/themes/hi-vis/${mode}/**/*.json`],
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath: 'dist/css/',
        files: [{ destination, format: 'css/variables', options: { selector } }],
      },
    },
  });

  await sd.buildAllPlatforms();
}

await buildDefault('light', ':root', 'default-light.css');

await buildDefault('dark', '[data-theme="dark"]', 'default-dark.css');

const combined = [
  readFileSync('dist/css/default-light.css', 'utf8'),
  readFileSync('dist/css/default-dark.css', 'utf8'),
  ...PRESETS.flatMap((preset) =>
    MODES.map((mode) => readFileSync(`dist/css/${preset}-${mode}.css`, 'utf8')),
  ),
].join('\n');
writeFileSync(
  'dist/css/tokens.css',
  `/* Generated by build.mjs — do not edit by hand. */\n\n${combined}`,
);

console.log(
  `Tokens built: dist/css/tokens.css, src/generated/{${PRESETS.map((p) => `${p}-{light,dark}`).join(',')}}.ts`,
);
